[package]
name = "tapir-tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
env_logger = "0.11.8"
log = "0.4.27"
catppuccin-egui = { version = "5.5.0", default-features = false, features = [
    "egui31",
] }
